theme: minima
title: Victoria's Portfolio
author: Victoria Geh
email: victoriageh@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to bullet journals and videos, healthy recipes
  and whatever else I come up during social distancing.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
